// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package comms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Juego1Client is the client API for Juego1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Juego1Client interface {
	Jugada1(ctx context.Context, in *JugadorJuego1, opts ...grpc.CallOption) (*EstadoJuego, error)
}

type juego1Client struct {
	cc grpc.ClientConnInterface
}

func NewJuego1Client(cc grpc.ClientConnInterface) Juego1Client {
	return &juego1Client{cc}
}

func (c *juego1Client) Jugada1(ctx context.Context, in *JugadorJuego1, opts ...grpc.CallOption) (*EstadoJuego, error) {
	out := new(EstadoJuego)
	err := c.cc.Invoke(ctx, "/comms.Juego1/Jugada1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Juego1Server is the server API for Juego1 service.
// All implementations must embed UnimplementedJuego1Server
// for forward compatibility
type Juego1Server interface {
	Jugada1(context.Context, *JugadorJuego1) (*EstadoJuego, error)
	mustEmbedUnimplementedJuego1Server()
}

// UnimplementedJuego1Server must be embedded to have forward compatible implementations.
type UnimplementedJuego1Server struct {
}

func (UnimplementedJuego1Server) Jugada1(context.Context, *JugadorJuego1) (*EstadoJuego, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Jugada1 not implemented")
}
func (UnimplementedJuego1Server) mustEmbedUnimplementedJuego1Server() {}

// UnsafeJuego1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Juego1Server will
// result in compilation errors.
type UnsafeJuego1Server interface {
	mustEmbedUnimplementedJuego1Server()
}

func RegisterJuego1Server(s grpc.ServiceRegistrar, srv Juego1Server) {
	s.RegisterService(&Juego1_ServiceDesc, srv)
}

func _Juego1_Jugada1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JugadorJuego1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Juego1Server).Jugada1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Juego1/Jugada1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Juego1Server).Jugada1(ctx, req.(*JugadorJuego1))
	}
	return interceptor(ctx, in, info, handler)
}

// Juego1_ServiceDesc is the grpc.ServiceDesc for Juego1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Juego1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comms.Juego1",
	HandlerType: (*Juego1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Jugada1",
			Handler:    _Juego1_Jugada1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comms.proto",
}
