// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: comms.proto

package comms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JugadorJuego1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EscogidoJugador int32 `protobuf:"varint,1,opt,name=escogidoJugador,proto3" json:"escogidoJugador,omitempty"` // debe estar entre 1 y 10
}

func (x *JugadorJuego1) Reset() {
	*x = JugadorJuego1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadorJuego1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadorJuego1) ProtoMessage() {}

func (x *JugadorJuego1) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadorJuego1.ProtoReflect.Descriptor instead.
func (*JugadorJuego1) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{0}
}

func (x *JugadorJuego1) GetEscogidoJugador() int32 {
	if x != nil {
		return x.EscogidoJugador
	}
	return 0
}

type EstadoJuego struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vivo          bool  `protobuf:"varint,1,opt,name=vivo,proto3" json:"vivo,omitempty"`                   // define si murio
	EscogidoLider int32 `protobuf:"varint,2,opt,name=escogidoLider,proto3" json:"escogidoLider,omitempty"` // entre 6 y 10
	Win           bool  `protobuf:"varint,3,opt,name=win,proto3" json:"win,omitempty"`                     // define si gano
	Round         int32 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *EstadoJuego) Reset() {
	*x = EstadoJuego{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoJuego) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoJuego) ProtoMessage() {}

func (x *EstadoJuego) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoJuego.ProtoReflect.Descriptor instead.
func (*EstadoJuego) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{1}
}

func (x *EstadoJuego) GetVivo() bool {
	if x != nil {
		return x.Vivo
	}
	return false
}

func (x *EstadoJuego) GetEscogidoLider() int32 {
	if x != nil {
		return x.EscogidoLider
	}
	return 0
}

func (x *EstadoJuego) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *EstadoJuego) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type MontoAcumulado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto int64 `protobuf:"varint,1,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *MontoAcumulado) Reset() {
	*x = MontoAcumulado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MontoAcumulado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoAcumulado) ProtoMessage() {}

func (x *MontoAcumulado) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoAcumulado.ProtoReflect.Descriptor instead.
func (*MontoAcumulado) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{2}
}

func (x *MontoAcumulado) GetMonto() int64 {
	if x != nil {
		return x.Monto
	}
	return 0
}

type JugadaDataNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugador int32 `protobuf:"varint,1,opt,name=jugador,proto3" json:"jugador,omitempty"`
	Ronda   int32 `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Jugada  int32 `protobuf:"varint,3,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *JugadaDataNode) Reset() {
	*x = JugadaDataNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadaDataNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadaDataNode) ProtoMessage() {}

func (x *JugadaDataNode) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadaDataNode.ProtoReflect.Descriptor instead.
func (*JugadaDataNode) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{3}
}

func (x *JugadaDataNode) GetJugador() int32 {
	if x != nil {
		return x.Jugador
	}
	return 0
}

func (x *JugadaDataNode) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *JugadaDataNode) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

type Jugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJug int32 `protobuf:"varint,1,opt,name=numJug,proto3" json:"numJug,omitempty"`
}

func (x *Jugador) Reset() {
	*x = Jugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador) ProtoMessage() {}

func (x *Jugador) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador.ProtoReflect.Descriptor instead.
func (*Jugador) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{4}
}

func (x *Jugador) GetNumJug() int32 {
	if x != nil {
		return x.NumJug
	}
	return 0
}

type HistorialJugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugador int32   `protobuf:"varint,1,opt,name=jugador,proto3" json:"jugador,omitempty"`
	Ronda1  []int32 `protobuf:"varint,2,rep,packed,name=ronda1,proto3" json:"ronda1,omitempty"`
	Ronda2  []int32 `protobuf:"varint,3,rep,packed,name=ronda2,proto3" json:"ronda2,omitempty"`
	Ronda3  []int32 `protobuf:"varint,4,rep,packed,name=ronda3,proto3" json:"ronda3,omitempty"`
	Jugada  int32   `protobuf:"varint,5,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *HistorialJugadas) Reset() {
	*x = HistorialJugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistorialJugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistorialJugadas) ProtoMessage() {}

func (x *HistorialJugadas) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistorialJugadas.ProtoReflect.Descriptor instead.
func (*HistorialJugadas) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{5}
}

func (x *HistorialJugadas) GetJugador() int32 {
	if x != nil {
		return x.Jugador
	}
	return 0
}

func (x *HistorialJugadas) GetRonda1() []int32 {
	if x != nil {
		return x.Ronda1
	}
	return nil
}

func (x *HistorialJugadas) GetRonda2() []int32 {
	if x != nil {
		return x.Ronda2
	}
	return nil
}

func (x *HistorialJugadas) GetRonda3() []int32 {
	if x != nil {
		return x.Ronda3
	}
	return nil
}

func (x *HistorialJugadas) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{6}
}

var File_comms_proto protoreflect.FileDescriptor

var file_comms_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6f, 0x6d, 0x6d, 0x73, 0x22, 0x39, 0x0a, 0x0d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x4a,
	0x75, 0x65, 0x67, 0x6f, 0x31, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x73, 0x63, 0x6f, 0x67, 0x69, 0x64,
	0x6f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x65, 0x73, 0x63, 0x6f, 0x67, 0x69, 0x64, 0x6f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22,
	0x6f, 0x0a, 0x0b, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x69, 0x76, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x76, 0x69,
	0x76, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x73, 0x63, 0x6f, 0x67, 0x69, 0x64, 0x6f, 0x4c, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x65, 0x73, 0x63, 0x6f, 0x67,
	0x69, 0x64, 0x6f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x22, 0x26, 0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x41, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61,
	0x64, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0e, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x22, 0x21, 0x0a, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x4a, 0x75, 0x67, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x69, 0x61, 0x6c, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x31, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x31, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6e, 0x64, 0x61, 0x32, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f,
	0x6e, 0x64, 0x61, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x33, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x33, 0x12, 0x16, 0x0a, 0x06,
	0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x3f, 0x0a,
	0x06, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x31, 0x12, 0x35, 0x0a, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x31, 0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x6f, 0x72, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x31, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73,
	0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x22, 0x00, 0x32, 0x82,
	0x01, 0x0a, 0x10, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x15, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x10, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x61,
	0x6c, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73,
	0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73,
	0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x73, 0x22, 0x00, 0x32, 0x3b, 0x0a, 0x04, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x33, 0x0a, 0x0a, 0x50,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e,
	0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x41, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x22, 0x00,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comms_proto_rawDescOnce sync.Once
	file_comms_proto_rawDescData = file_comms_proto_rawDesc
)

func file_comms_proto_rawDescGZIP() []byte {
	file_comms_proto_rawDescOnce.Do(func() {
		file_comms_proto_rawDescData = protoimpl.X.CompressGZIP(file_comms_proto_rawDescData)
	})
	return file_comms_proto_rawDescData
}

var file_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_comms_proto_goTypes = []interface{}{
	(*JugadorJuego1)(nil),    // 0: comms.JugadorJuego1
	(*EstadoJuego)(nil),      // 1: comms.EstadoJuego
	(*MontoAcumulado)(nil),   // 2: comms.MontoAcumulado
	(*JugadaDataNode)(nil),   // 3: comms.JugadaDataNode
	(*Jugador)(nil),          // 4: comms.Jugador
	(*HistorialJugadas)(nil), // 5: comms.HistorialJugadas
	(*Empty)(nil),            // 6: comms.Empty
}
var file_comms_proto_depIdxs = []int32{
	0, // 0: comms.Juego1.Jugada1:input_type -> comms.JugadorJuego1
	3, // 1: comms.MensajeDataLider.Jugada:input_type -> comms.JugadaDataNode
	4, // 2: comms.MensajeDataLider.HistorialJugador:input_type -> comms.Jugador
	6, // 3: comms.Pozo.PedidoPozo:input_type -> comms.Empty
	1, // 4: comms.Juego1.Jugada1:output_type -> comms.EstadoJuego
	6, // 5: comms.MensajeDataLider.Jugada:output_type -> comms.Empty
	5, // 6: comms.MensajeDataLider.HistorialJugador:output_type -> comms.HistorialJugadas
	2, // 7: comms.Pozo.PedidoPozo:output_type -> comms.MontoAcumulado
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comms_proto_init() }
func file_comms_proto_init() {
	if File_comms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadorJuego1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoJuego); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MontoAcumulado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadaDataNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistorialJugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_comms_proto_goTypes,
		DependencyIndexes: file_comms_proto_depIdxs,
		MessageInfos:      file_comms_proto_msgTypes,
	}.Build()
	File_comms_proto = out.File
	file_comms_proto_rawDesc = nil
	file_comms_proto_goTypes = nil
	file_comms_proto_depIdxs = nil
}
